# Generated by Django 4.2.20 on 2025-04-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResumeAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume", models.FileField(upload_to="resumes/")),
                ("job_description", models.TextField()),
                ("candidate_email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("match_score", models.FloatField(blank=True, null=True)),
                ("matching_skills", models.JSONField(blank=True, null=True)),
                ("missing_skills", models.JSONField(blank=True, null=True)),
                ("experience_match", models.FloatField(blank=True, null=True)),
                ("education_match", models.FloatField(blank=True, null=True)),
                ("recommendations", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
