# Generated by Django 4.2.20 on 2025-04-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resumeanalysis",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Resume Analyses",
            },
        ),
        migrations.AlterField(
            model_name="resumeanalysis",
            name="matching_skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="resumeanalysis",
            name="missing_skills",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="resumeanalysis",
            name="recommendations",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
