# Generated by Django 4.2.20 on 2025-04-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_analyzer", "0002_alter_resumeanalysis_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeanalysis",
            name="recruiter_email",
            field=models.EmailField(default="default@gmail.com", max_length=254),
        ),
    ]
